**Import CIFAR-100 dataset**

In [1]:
import torch
import torchvision
import torchvision.transforms as transforms
import numpy as np

class IMBALANCECIFAR10(torchvision.datasets.CIFAR10):
    cls_num = 10

    def __init__(self, root, imb_type='exp', imb_factor=0.01, rand_number=0, train=True,
                 transform=None, target_transform=None,
                 download=False):
        super(IMBALANCECIFAR10, self).__init__(root, train, transform, target_transform, download)
        np.random.seed(rand_number)
        img_num_list = self.get_img_num_per_cls(self.cls_num, imb_type, imb_factor)
        self.gen_imbalanced_data(img_num_list)

    def get_img_num_per_cls(self, cls_num, imb_type, imb_factor):
        img_max = len(self.data) / cls_num
        img_num_per_cls = []
        if imb_type == 'exp':
            for cls_idx in range(cls_num):
                num = img_max * (imb_factor**(cls_idx / (cls_num - 1.0)))
                img_num_per_cls.append(int(num))
        elif imb_type == 'step':
            for cls_idx in range(cls_num // 2):
                img_num_per_cls.append(int(img_max))
            for cls_idx in range(cls_num // 2):
                img_num_per_cls.append(int(img_max * imb_factor))
        else:
            img_num_per_cls.extend([int(img_max)] * cls_num)
        return img_num_per_cls

    def gen_imbalanced_data(self, img_num_per_cls):
        new_data = []
        new_targets = []
        targets_np = np.array(self.targets, dtype=np.int64)
        classes = np.unique(targets_np)
        # np.random.shuffle(classes)
        self.num_per_cls_dict = dict()
        for the_class, the_img_num in zip(classes, img_num_per_cls):
            self.num_per_cls_dict[the_class] = the_img_num
            idx = np.where(targets_np == the_class)[0]
            np.random.shuffle(idx)
            selec_idx = idx[:the_img_num]
            new_data.append(self.data[selec_idx, ...])
            new_targets.extend([the_class, ] * the_img_num)
        new_data = np.vstack(new_data)
        self.data = new_data
        self.targets = new_targets
        
    def get_cls_num_list(self):
        cls_num_list = []
        for i in range(self.cls_num):
            cls_num_list.append(self.num_per_cls_dict[i])
        return cls_num_list

In [2]:
def create_sampled_CIFAR10_data():

    transform_train = transforms.Compose([
            transforms.RandomCrop(32, padding=4),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
        ])

    transform_val = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
        ])

    trainset = IMBALANCECIFAR10(root='./data', train=True, download=True, transform=transform_train)
    testset = IMBALANCECIFAR10(root='./data', train=False, download=True, transform=transform_val)

    trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True, num_workers=2)    
    testloader = torch.utils.data.DataLoader(testset, batch_size=100, shuffle=False, num_workers=2)

    return trainset, trainloader, testset, testloader

In [3]:
trainset, trainloader, testset, testloader = create_sampled_CIFAR10_data()

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [4]:
def create_class_subsets(trainset, shuffle=True, batch_size=128):
    
    labels = np.array(trainset.targets)
    
    trainset_0 = torch.utils.data.Subset(trainset, list(np.where(labels == 0)[0]))
    trainset_1 = torch.utils.data.Subset(trainset, list(np.where(labels == 1)[0]))
    trainset_2 = torch.utils.data.Subset(trainset, list(np.where(labels == 2)[0]))
    trainset_3 = torch.utils.data.Subset(trainset, list(np.where(labels == 3)[0]))
    trainset_4 = torch.utils.data.Subset(trainset, list(np.where(labels == 4)[0]))
    trainset_5 = torch.utils.data.Subset(trainset, list(np.where(labels == 5)[0]))
    trainset_6 = torch.utils.data.Subset(trainset, list(np.where(labels == 6)[0]))
    trainset_7 = torch.utils.data.Subset(trainset, list(np.where(labels == 7)[0]))
    trainset_8 = torch.utils.data.Subset(trainset, list(np.where(labels == 8)[0]))
    trainset_9 = torch.utils.data.Subset(trainset, list(np.where(labels == 9)[0]))

    trainsets = [trainset_0, trainset_1, trainset_2, trainset_3, trainset_4, trainset_5, trainset_6, trainset_7, trainset_8, trainset_9]

    trainloader_0 = torch.utils.data.DataLoader(trainset_0, batch_size=batch_size, shuffle=shuffle, num_workers=2)
    trainloader_1 = torch.utils.data.DataLoader(trainset_1, batch_size=batch_size, shuffle=shuffle, num_workers=2)
    trainloader_2 = torch.utils.data.DataLoader(trainset_2, batch_size=batch_size, shuffle=shuffle, num_workers=2)
    trainloader_3 = torch.utils.data.DataLoader(trainset_3, batch_size=batch_size, shuffle=shuffle, num_workers=2)
    trainloader_4 = torch.utils.data.DataLoader(trainset_4, batch_size=batch_size, shuffle=shuffle, num_workers=2)
    trainloader_5 = torch.utils.data.DataLoader(trainset_5, batch_size=batch_size, shuffle=shuffle, num_workers=2)
    trainloader_6 = torch.utils.data.DataLoader(trainset_6, batch_size=batch_size, shuffle=shuffle, num_workers=2)
    trainloader_7 = torch.utils.data.DataLoader(trainset_7, batch_size=batch_size, shuffle=shuffle, num_workers=2)
    trainloader_8 = torch.utils.data.DataLoader(trainset_8, batch_size=batch_size, shuffle=shuffle, num_workers=2)
    trainloader_9 = torch.utils.data.DataLoader(trainset_9, batch_size=batch_size, shuffle=shuffle, num_workers=2)

    trainloaders = [trainloader_0, trainloader_1, trainloader_2, trainloader_3, trainloader_4, trainloader_5, trainloader_6, trainloader_7, trainloader_8, trainloader_9]

    return trainsets, trainloaders


In [ ]:
trainset_0, trainset_1, trainset_2, trainset_3, trainset_4, trainset_5, trainset_6, trainset_7, trainset_8, trainset_9, trainloader_0, trainloader_1, trainloader_2, trainloader_3, trainloader_4, trainloader_5, trainloader_6, trainloader_7, trainloader_8, trainloader_9 = create_class_subsets(trainset, shuffle=True, batch_size=128)
testset_0, testset_1, testset_2, testset_3, testset_4, testset_5, testset_6, testset_7, testset_8, testset_9, testloader_0, testloader_1, testloader_2, testloader_3, testloader_4, testloader_5, testloader_6, testloader_7, testloader_8, testloader_9 = create_class_subsets(testset, shuffle=False, batch_size=100)

print(len(testset_1))

599


**Creating ResNet model**

In [5]:
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor
from typing import Type, Any, Callable, Union, List, Optional

In [6]:
def conv3x3(in_planes: int, out_planes: int, stride: int = 1, groups: int = 1, dilation: int = 1) -> nn.Conv2d:
    '''
    Implementation is taken from the PyTorch GitHub repository
    https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
    '''

    """3x3 convolution with padding"""
    return nn.Conv2d(in_planes, out_planes, kernel_size=3, stride=stride,
                     padding=dilation, groups=groups, bias=False, dilation=dilation)


def conv1x1(in_planes: int, out_planes: int, stride: int = 1) -> nn.Conv2d:
    '''
    Implementation is taken from the PyTorch GitHub repository
    https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
    '''    
    
    """1x1 convolution"""
    return nn.Conv2d(in_planes, out_planes, kernel_size=1, stride=stride, bias=False)

In [7]:
class BasicBlock(nn.Module):
    '''
    Implementation is taken from the PyTorch GitHub repository
    https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
    '''
    
    expansion: int = 1

    def __init__(self, inplanes: int, planes: int, stride: int = 1, downsample: Optional[nn.Module] = None, groups: int = 1, base_width: int = 64, dilation: int = 1, norm_layer: Optional[Callable[..., nn.Module]] = None) -> None:
        super(BasicBlock, self).__init__()
        
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        
        if groups != 1 or base_width != 64:
            raise ValueError('BasicBlock only supports groups=1 and base_width=64')
        
        if dilation > 1:
            raise NotImplementedError("Dilation > 1 not supported in BasicBlock")
        
        # Both self.conv1 and self.downsample layers downsample the input when stride != 1
        self.conv1 = conv3x3(inplanes, planes, stride)
        self.bn1 = norm_layer(planes)
        self.relu = nn.ReLU(inplace=True)
        self.conv2 = conv3x3(planes, planes)
        self.bn2 = norm_layer(planes)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x: Tensor) -> Tensor:
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out

In [8]:
class Bottleneck(nn.Module):
    '''
    Implementation is taken from the PyTorch GitHub repository
    https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
    '''

    # Bottleneck in torchvision places the stride for downsampling at 3x3 convolution(self.conv2)
    # while original implementation places the stride at the first 1x1 convolution(self.conv1)
    # according to "Deep residual learning for image recognition"https://arxiv.org/abs/1512.03385.
    # This variant is also known as ResNet V1.5 and improves accuracy according to
    # https://ngc.nvidia.com/catalog/model-scripts/nvidia:resnet_50_v1_5_for_pytorch.

    expansion: int = 4

    def __init__(self, inplanes: int, planes: int, stride: int = 1, downsample: Optional[nn.Module] = None, groups: int = 1, base_width: int = 64, dilation: int = 1, norm_layer: Optional[Callable[..., nn.Module]] = None) -> None:
        super(Bottleneck, self).__init__()
        
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        
        width = int(planes * (base_width / 64.)) * groups
        
        # Both self.conv2 and self.downsample layers downsample the input when stride != 1
        self.conv1 = conv1x1(inplanes, width)
        self.bn1 = norm_layer(width)
        self.conv2 = conv3x3(width, width, stride, groups, dilation)
        self.bn2 = norm_layer(width)
        self.conv3 = conv1x1(width, planes * self.expansion)
        self.bn3 = norm_layer(planes * self.expansion)
        self.relu = nn.ReLU(inplace=True)
        self.downsample = downsample
        self.stride = stride

    def forward(self, x: Tensor) -> Tensor:
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.relu(out)

        out = self.conv3(out)
        out = self.bn3(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out

In [9]:
class ResNet(nn.Module):
    '''
    Implementation is taken from the PyTorch GitHub repository
    https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py
    '''


    def __init__(self, block: Type[Union[BasicBlock, Bottleneck]], layers: List[int], num_classes: int = 1000, zero_init_residual: bool = False, groups: int = 1, width_per_group: int = 64, replace_stride_with_dilation: Optional[List[bool]] = None, norm_layer: Optional[Callable[..., nn.Module]] = None) -> None:
        super(ResNet, self).__init__()
        
        if norm_layer is None:
            norm_layer = nn.BatchNorm2d
        
        self._norm_layer = norm_layer

        self.inplanes = 64
        self.dilation = 1
        
        if replace_stride_with_dilation is None:
            # each element in the tuple indicates if we should replace
            # the 2x2 stride with a dilated convolution instead
            replace_stride_with_dilation = [False, False, False]
        
        if len(replace_stride_with_dilation) != 3:
            raise ValueError("replace_stride_with_dilation should be None "
                             "or a 3-element tuple, got {}".format(replace_stride_with_dilation))
        
        self.groups = groups
        self.base_width = width_per_group
        
        self.conv1 = nn.Conv2d(3, self.inplanes, kernel_size=7, stride=2, padding=3,
                               bias=False)
        self.bn1 = norm_layer(self.inplanes)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)
        self.layer1 = self._make_layer(block, 64, layers[0])
        self.layer2 = self._make_layer(block, 128, layers[1], stride=2,
                                       dilate=replace_stride_with_dilation[0])
        self.layer3 = self._make_layer(block, 256, layers[2], stride=2,
                                       dilate=replace_stride_with_dilation[1])
        self.layer4 = self._make_layer(block, 512, layers[3], stride=2,
                                       dilate=replace_stride_with_dilation[2])
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(512 * block.expansion, num_classes)

        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, (nn.BatchNorm2d, nn.GroupNorm)):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

        # Zero-initialize the last BN in each residual branch,
        # so that the residual branch starts with zeros, and each residual block behaves like an identity.
        # This improves the model by 0.2~0.3% according to https://arxiv.org/abs/1706.02677
        if zero_init_residual:
            for m in self.modules():
                if isinstance(m, Bottleneck):
                    nn.init.constant_(m.bn3.weight, 0)  # type: ignore[arg-type]
                elif isinstance(m, BasicBlock):
                    nn.init.constant_(m.bn2.weight, 0)  # type: ignore[arg-type]


    def _make_layer(self, block: Type[Union[BasicBlock, Bottleneck]], planes: int, blocks: int,
                    stride: int = 1, dilate: bool = False) -> nn.Sequential:
        
        norm_layer = self._norm_layer
        downsample = None
        previous_dilation = self.dilation
        
        if dilate:
            self.dilation *= stride
            stride = 1
        
        if stride != 1 or self.inplanes != planes * block.expansion:
            downsample = nn.Sequential(
                conv1x1(self.inplanes, planes * block.expansion, stride),
                norm_layer(planes * block.expansion),
            )

        layers = []
        layers.append(block(self.inplanes, planes, stride, downsample, self.groups,
                            self.base_width, previous_dilation, norm_layer))
        
        self.inplanes = planes * block.expansion
        
        for _ in range(1, blocks):
            layers.append(block(self.inplanes, planes, groups=self.groups,
                                base_width=self.base_width, dilation=self.dilation,
                                norm_layer=norm_layer))

        return nn.Sequential(*layers)


    def _forward_impl(self, x: Tensor) -> Tensor:
        # See note [TorchScript super()]
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)

        return x


    def forward(self, x: Tensor) -> Tensor:
        return self._forward_impl(x)


In [10]:
def ResNet18():
    return ResNet(BasicBlock, [2,2,2,2], 10)

In [11]:
def train_congestion_avoider_10classes(cls_num, trainloader_full, trainloaders, device, model, optimizer, criterion, boolean_values, grads, epoch_counts):

    ''' 
        XXXX
    '''

    import copy

    model.train()
    start_time = time.time()

    confusion_matrix = np.zeros((cls_num, cls_num))

    for epoch_count, boolean in zip(epoch_counts, boolean_values):
        if boolean:
            epoch_count = 0
    
    # Run through each class data subset in turn and store their gradient
    for cls_num, trainloader in enumerate(trainloaders):
        for batch_idx, (inputs, targets) in enumerate(trainloader):
            inputs = inputs.to(device)
            targets = targets.to(device)
            optimizer.zero_grad()
        
            outputs = model(inputs)
            loss = criterion(outputs,targets)
        
            # Back-propagate the loss due to 'cats'
            loss.backward(retain_graph=False)
            with torch.no_grad():
                for name, parameter in model.named_parameters():
                  try:
                      if name not in grads[cls_num].keys():
                          grads[cls_num][name] = torch.mul(copy.deepcopy(parameter.grad), optimizer.param_groups[0]['lr'])
                      else:
                          grads[cls_num][name] += torch.mul(copy.deepcopy(parameter.grad), optimizer.param_groups[0]['lr'])
                  except:
                      pass
            
    # Then update the weights by running through the full shuffled dataset
    # Using the class subsets would be ordered training data which is not good practice
    for batch_idx, (inputs, targets) in enumerate(trainloader_full):
        inputs = inputs.to(device)
        targets = targets.to(device)
        outputs = model(inputs)
        optimizer.zero_grad()
        loss = criterion(outputs,targets)
        loss.backward(retain_graph=True)
        optimizer.step()

        _, predicted = outputs.max(1)

        for target, pred in zip(targets, predicted):
            confusion_matrix[target][pred] += 1

    recalls = np.zeros((10))
    precisions = np.zeros((10))
    fScores = np.zeros((10))

    epoch_counts = [x+1 for x in epoch_counts]

    for cls in range(cls_num):
      try:
          recalls[cls] = confusion_matrix[cls][cls] / confusion_matrix.sum(1)[cls]
      except:
          recalls[cls] = 0
      try:
          precisions[cls] = confusion_matrix[cls][cls] / confusion_matrix.sum(0)[cls]
      except:
          precisions[cls] = 0
      try:
          fScores[cls] = 2 * precisions[cls] * recalls[cls] / (precisions[cls] + recalls[cls])
      except:
          fScores[cls] = 0

    accuracy = np.trace(confusion_matrix) / confusion_matrix.sum()

    return confusion_matrix, accuracy, recalls, precisions, fScores, grads, epoch_counts

In [15]:
def train_congestion_avoider_10classes_debug(cls_num, trainloader_full, trainloaders, device, model, optimizer, criterion, boolean_values, grads, epoch_counts):

    ''' 
        XXXX
    '''

    import copy

    model.train()
    start_time = time.time()
    total_grads = {}

    confusion_matrix = np.zeros((cls_num, cls_num))

    for epoch_count, boolean in zip(epoch_counts, boolean_values):
        if boolean:
            epoch_count = 0
    
    # Run through each class data subset in turn and store their gradient
    for cls_num, trainloader in enumerate(trainloaders):
        inputs, targets = next(iter(trainloader))
        inputs_2, targets_2 = next(iter(trainloader))
        for index, (input, target) in enumerate(zip([inputs,inputs_2], [targets,targets_2])):
            inputs = input.to(device)
            targets = target.to(device)
            optimizer.zero_grad()
        
            outputs = model(inputs)
            loss = criterion(outputs,targets)
        
            # Back-propagate the loss due to 'cats'
            loss.backward(retain_graph=False)
            with torch.no_grad():
                for name, parameter in model.named_parameters():
                  try:
                      if name not in grads[cls_num].keys():
                          grads[cls_num][name] = torch.mul(copy.deepcopy(parameter.grad), optimizer.param_groups[0]['lr'])
                      else:
                          grads[cls_num][name] += torch.mul(copy.deepcopy(parameter.grad), optimizer.param_groups[0]['lr'])
                  except:
                      pass
        print('Class {} backward conv1 grad: '.format(cls_num), torch.sum(grads[cls_num]['module.conv1.weight']))
            
    # Then update the weights by running through the full shuffled dataset
    # Using the class subsets would be ordered training data which is not good practice
    inputs, targets = next(iter(trainloader))
    inputs_2, targets_2 = next(iter(trainloader))
    
    for index, (input, target) in enumerate(zip([inputs,inputs_2], [targets,targets_2])):
        inputs = input.to(device)
        targets = target.to(device)
        outputs = model(inputs)
        optimizer.zero_grad()
        loss = criterion(outputs,targets)
        loss.backward(retain_graph=True)
        with torch.no_grad():
            for name, parameter in model.named_parameters():
                try:
                    if name not in total_grads.keys():
                        total_grads[name] = torch.mul(copy.deepcopy(parameter.grad), optimizer.param_groups[0]['lr'])
                    else:
                        total_grads[name] += torch.mul(copy.deepcopy(parameter.grad), optimizer.param_groups[0]['lr'])
                except:
                    pass
        optimizer.step()

        _, predicted = outputs.max(1)

        for target, pred in zip(targets, predicted):
            confusion_matrix[target][pred] += 1

    recalls = np.zeros((10))
    precisions = np.zeros((10))
    fScores = np.zeros((10))

    epoch_counts = [x+1 for x in epoch_counts]

    for cls in range(cls_num):
      try:
          recalls[cls] = confusion_matrix[cls][cls] / confusion_matrix.sum(1)[cls]
      except:
          recalls[cls] = 0
      try:
          precisions[cls] = confusion_matrix[cls][cls] / confusion_matrix.sum(0)[cls]
      except:
          precisions[cls] = 0
      try:
          fScores[cls] = 2 * precisions[cls] * recalls[cls] / (precisions[cls] + recalls[cls])
      except:
          fScores[cls] = 0

    accuracy = np.trace(confusion_matrix) / confusion_matrix.sum()

    return confusion_matrix, accuracy, recalls, precisions, fScores, grads, epoch_counts

In [12]:
def linear_cong_condition(min_cond, max_cond, epoch, max_epochs):

    condition = min_cond + (max_cond - min_cond) * (epoch / max_epochs)

    return condition

In [13]:
def congestion_avoid_10classes(cls_num, model, optimizer, metrics, condition, grads, min_epochs, mult, epoch_counts, boolean_values):

    for cls in range(cls_num):
        metric = metrics[cls]
        if any(other_metric < condition * metric for other_metric in metrics):
            boolean_values[cls] = True
            print('Class {} Condition has been met ..... {:.2f}%'%(cls,100.*condition))
            for name, value in model.named_parameters():
                with torch.no_grad():
                    if name in grads[cls].keys():
                        value += mult * grads[cls][name]
            for name in grads[cls].keys():
                grads[cls][name] -= mult * grads[cls][name]
            epoch_counts[cls_num] = 0
    
    else:
        print('No condition is met ..... {:.2f}%'.format(100.*condition))

    return optimizer, model, boolean_values, epoch_counts, grads

In [17]:
def congestion_avoid_10classes_minGradThreshold(cls_num, model, optimizer, metrics, condition, grads, min_epochs, mult, epoch_counts, boolean_values, num_class_avg, min_gradient):

    # Create a threshold which is the average metric from a number of the worst performing classes
    threshold = np.average(np.sort(metrics)[:num_class_avg])
    print('Average metrics value: {:.2f}%'.format(100.*threshold))

    for cls in range(cls_num):
        metric = metrics[cls]
        # If the metric of this class is sufficiently above the average of the worst classes
        # then the knowledge from that class is returned
        if (threshold < condition * metric) and (epoch_counts[cls] >= min_epochs):
            boolean_values[cls] = True
            print('Condition has been met (class {}) ..... {:.2f}% --> {:.2f}%'.format(cls,100.*threshold, 100.*metric))
            for name, value in model.named_parameters():
                with torch.no_grad():
                    if name in grads[cls].keys():
                        if torch.min(abs(grads[cls][name])) > min_gradient:
                            value += mult * grads[cls][name]
                            grads[cls][name] -= mult * grads[cls][name]
            epoch_counts[cls] = 0
        else:
            print('Condition not met (class {}) ..... {:.2f}% --> {:.2f}%'.format(cls,100.*threshold, 100.*metric))

    return optimizer, model, boolean_values, epoch_counts, grads

In [15]:
def congestion_avoid_10classes_minGradThreshold_v2(cls_num, model, optimizer, metrics, condition, grads, min_epochs, mult, epoch_counts, boolean_values, num_class_avg, min_gradient):

    # Create a threshold which is the average metric from a number of the worst performing classes
    threshold = np.average(np.sort(metrics)[:num_class_avg])

    total_grad = {'layer1': {0:0, 1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 'total':0},
                  'layer2': {0:0, 1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 'total':0},
                  'layer3': {0:0, 1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 'total':0},
                  'layer4': {0:0, 1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 'total':0},
                  'conv1': {0:0, 1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 'total':0},
                  'bn1': {0:0, 1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 'total':0},
                  'fc': {0:0, 1:0, 2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 'total':0}
                  }

    print('TOTAL GRAIDENTS:')

    for cls in range(cls_num):
        for name, value in model.named_parameters():
            if 'layer1' in str(name):
                total_grad['layer1'][cls] += float(abs(grads[cls][name]).sum())
                total_grad['layer1']['total'] += float(abs(grads[cls][name]).sum())
            elif 'layer2' in str(name):
                total_grad['layer2'][cls] += float(abs(grads[cls][name]).sum())
                total_grad['layer2']['total'] += float(abs(grads[cls][name]).sum())
            elif 'layer3' in str(name):
                total_grad['layer3'][cls] += float(abs(grads[cls][name]).sum())
                total_grad['layer3']['total'] += float(abs(grads[cls][name]).sum())
            elif 'layer4' in str(name):
                total_grad['layer4'][cls] += float(abs(grads[cls][name]).sum())
                total_grad['layer4']['total'] += float(abs(grads[cls][name]).sum())
            elif 'conv1' in str(name):
                total_grad['conv1'][cls] += float(abs(grads[cls][name]).sum())
                total_grad['conv1']['total'] += float(abs(grads[cls][name]).sum())
            elif 'bn1' in str(name):
                total_grad['bn1'][cls] += float(abs(grads[cls][name]).sum())
                total_grad['bn1']['total'] += float(abs(grads[cls][name]).sum())
            elif 'fc' in str(name):
                total_grad['fc'][cls] += float(abs(grads[cls][name]).sum())
                total_grad['fc']['total'] += float(abs(grads[cls][name]).sum())
    print(total_grad)

    for cls in range(cls_num):
        metric = metrics[cls]
        # If the metric of this class is sufficiently above the average of the worst classes
        # And the gradient of that layer is significant compared to the other classes
        # then the knowledge from that class is returned
        if (threshold < condition * metric) and (epoch_counts[cls] >= min_epochs):
            boolean_values[cls] = True
            print('Condition has been met (class {}) ..... {:.2f}% --> {:.2f}%'.format(cls,100.*threshold, 100.*metric))
            for name, value in model.named_parameters():
                with torch.no_grad():
                  # ADDED CONDITION TO ONLY CHANGE GRADIENTS FROM LAYER 3 ONWARDS
                    if name in grads[cls].keys() and (('layer4' in str(name)) or ('fc' in str(name))):
                        if ('layer1' in str(name)) and (total_grad['layer1'][cls] > min_gradient * total_grad['layer1']['total']):
                            value += mult * grads[cls][name]
                            grads[cls][name] -= mult * grads[cls][name]
                        elif ('layer2' in str(name)) and (total_grad['layer2'][cls] > min_gradient * total_grad['layer2']['total']):
                            value += mult * grads[cls][name]
                            grads[cls][name] -= mult * grads[cls][name]
                        elif ('layer3' in str(name)) and (total_grad['layer3'][cls] > min_gradient * total_grad['layer3']['total']):
                            value += mult * grads[cls][name]
                            grads[cls][name] -= mult * grads[cls][name]
                        elif ('layer4' in str(name)) and (total_grad['layer4'][cls] > min_gradient * total_grad['layer4']['total']):
                            value += mult * grads[cls][name]
                            grads[cls][name] -= mult * grads[cls][name]
                        elif ('conv1' in str(name)) and (total_grad['conv1'][cls] > min_gradient * total_grad['conv1']['total']):
                            value += mult * grads[cls][name]
                            grads[cls][name] -= mult * grads[cls][name]
                        elif ('bn1' in str(name)) and (total_grad['bn1'][cls] > min_gradient * total_grad['bn1']['total']):
                            value += mult * grads[cls][name]
                            grads[cls][name] -= mult * grads[cls][name]
                        elif ('fc' in str(name)) and (total_grad['fc'][cls] > min_gradient * total_grad['fc']['total']):
                            value += mult * grads[cls][name]
                            grads[cls][name] -= mult * grads[cls][name]
                        else:
                            print('Gradient not significant: ', name)
                            pass
            epoch_counts[cls] = 0
    
        else:
            print('Condition not met (class {}) ..... {:.2f}% --> {:.2f}%'.format(cls,100.*threshold, 100.*metric))

    return optimizer, model, boolean_values, epoch_counts, grads

In [16]:
def test_congestion_avoider_10classes(cls_num, start_time, testloaders, device, model, optimizer, scheduler, grads, criterion, epoch, max_epochs, min_cond, max_cond, min_epochs, mult, epoch_counts, num_class_avg, min_gradient):

    ''' 
        XXXX
    '''

    import copy

    model.eval()
    confusion_matrix = np.zeros((cls_num, cls_num))
    recalls = np.zeros((10))
    precisions = np.zeros((10))
    fScores = np.zeros((10))
    boolean_values = np.zeros((10))
    
    with torch.no_grad():
        for cls_num, testloader in enumerate(testloaders):
            for batch_idx, (inputs, targets) in enumerate(testloader):
                inputs = inputs.to(device)
                targets = targets.to(device)
            
                outputs = model(inputs)
                loss = criterion(outputs,targets)
                _, predicted = outputs.max(1)

                for target, pred in zip(targets, predicted):
                    confusion_matrix[target][pred] += 1
    
        for cls in range(cls_num):
            if confusion_matrix.sum(1)[cls] != 0:
                recalls[cls] = confusion_matrix[cls][cls] / confusion_matrix.sum(1)[cls]
            else:
                recalls[cls] = 0
            if confusion_matrix.sum(0)[cls] != 0:
                precisions[cls] = confusion_matrix[cls][cls] / confusion_matrix.sum(0)[cls]
            else:
                precisions[cls] = 0
            if (precisions[cls] + recalls[cls]) != 0:
                fScores[cls] = 2 * precisions[cls] * recalls[cls] / (precisions[cls] + recalls[cls])
            else:
                fScores[cls] = 0

        accuracy = np.trace(confusion_matrix) / confusion_matrix.sum()
        
        condition = linear_cong_condition(min_cond, max_cond, epoch, max_epochs)
        
        optimizer, model, boolean_values, epoch_counts, grads = congestion_avoid_10classes_minGradThreshold_v2(cls_num, model, optimizer, precisions, condition, grads, min_epochs, mult, epoch_counts, boolean_values, num_class_avg, min_gradient)
        scheduler.step()

        print('time: %.3f sec'% ((time.time()-start_time)))
        print('Rows: Actual, Columns: Predicted')
        print(confusion_matrix)
        for cls in range(cls_num):
            print('Class %d A: : %.3f%% (%d/%d)'%(cls, 100*accuracy, np.trace(confusion_matrix), confusion_matrix.sum()))
            print('Class %d P: : %.3f%% (%d/%d)'%(cls, 100*precisions[cls], confusion_matrix[cls][cls], confusion_matrix.sum(1)[cls]))
            print('Class %d R: : %.3f%% (%d/%d)'%(cls, 100*recalls[cls], confusion_matrix[cls][cls], confusion_matrix.sum(0)[cls]))
            print('Class %d F: : %.3f%%'%(cls, 100*fScores[cls]))
            print('********************')


    return optimizer, accuracy, precisions, recalls, fScores, boolean_values, grads, epoch_counts

In [17]:
import torch.optim as optim
from torch.optim.lr_scheduler import CyclicLR
import time
import torch.backends.cudnn as cudnn

def get_cong_avoidance_results_10classes(epochs=100, min_cond=0.95, max_cond = 0.99, mult=1, lr=0.1, min_epochs = 5, num_class_avg = 8, min_gradient =0):

    '''Allow the congestion condition to change linearly over time '''

    # Create ResNet model
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    model = ResNet18()
    model = model.to(device)
    if device == 'cuda':
        print('CUDA device used...')
        model = torch.nn.DataParallel(model)
        cudnn.benchmark = True

    # Import data
    trainset_full, trainloader_full, testset_full, testloader_full = create_sampled_CIFAR10_data()
    trainsets, trainloaders = create_class_subsets(trainset_full, shuffle=True, batch_size=128)
    testsets, testloaders = create_class_subsets(testset_full, shuffle=False, batch_size=100)

    # Create variables
    cls_num = len(trainset_full.classes)
    boolean_values = [False]*cls_num
    grads = {}
    for cls in range(cls_num):
        grads[cls] = {}
    epoch_counts = [0]*cls_num
    
    criterion = nn.CrossEntropyLoss()
    # CREATE MODEL OPTIMIZER
    optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0, weight_decay=5e-4)
    scheduler = CyclicLR(optimizer, base_lr=0.0001, max_lr=lr, step_size_up=10, mode="triangular2")

    # BEGIN RECORDING THE TIME
    start_time = time.time()

    # Create matrices to store results

    train_acc = np.zeros((epochs, 1))
    train_P = np.zeros((epochs, cls_num))
    train_R = np.zeros((epochs, cls_num))
    train_F = np.zeros((epochs, cls_num))
    test_acc = np.zeros((epochs, 1))
    test_P = np.zeros((epochs, cls_num))
    test_R = np.zeros((epochs, cls_num))
    test_F = np.zeros((epochs, cls_num))
    cong_events = np.zeros((epochs, cls_num))

    for epoch in range(epochs):
        print('\n********** EPOCH {} **********'.format(epoch + 1))
        print('Learning rate: ', optimizer.param_groups[0]['lr'])
        print('Epoch counts: ', epoch_counts)
        confusion_matrix, accuracy, recalls, precisions, fScores, grads, epoch_counts = train_congestion_avoider_10classes(cls_num, trainloader_full, trainloaders, device, model, optimizer, criterion, boolean_values, grads, epoch_counts)
        train_acc[epoch] = accuracy
        train_P[epoch] = precisions
        train_R[epoch] = recalls
        train_F[epoch] = fScores
        optimizer, accuracy, precisions, recalls, fScores, boolean_values, grads, epoch_counts = test_congestion_avoider_10classes(cls_num, start_time, testloaders, device, model, optimizer, scheduler, grads, criterion, epoch, epochs, min_cond, max_cond, min_epochs, mult, epoch_counts, num_class_avg, min_gradient)
        test_acc[epoch] = accuracy
        test_P[epoch] = precisions
        test_R[epoch] = recalls
        test_F[epoch] = fScores
        cong_events[epoch] = boolean_values

    return train_acc, train_P, train_R, train_F, test_acc, test_P, test_R, test_F, cong_events

In [51]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
model = ResNet18()
model = model.to(device)
if device == 'cuda':
    print('CUDA device used...')
    model = torch.nn.DataParallel(model)
    cudnn.benchmark = True

# Import data
trainset_full, trainloader_full, testset_full, testloader_full = create_sampled_CIFAR10_data()
trainsets, trainloaders = create_class_subsets(trainset_full, shuffle=True, batch_size=128)
testsets, testloaders = create_class_subsets(testset_full, shuffle=False, batch_size=100)

# Create variables
cls_num = len(trainset_full.classes)
boolean_values = [False]*cls_num
grads = {}
for cls in range(cls_num):
    grads[cls] = {}
#grads = {0:{}, 1:{}, 2:{}, 3:{}, 4:{}, 5:{}, 6:{}, 7:{}, 8:{}, 9:{}}
epoch_counts = [0]*cls_num

lr=0.1

criterion = nn.CrossEntropyLoss()
# CREATE MODEL OPTIMIZER
optimizer = optim.SGD(model.parameters(), lr=lr, momentum=0, weight_decay=5e-4)
scheduler = CyclicLR(optimizer, base_lr=0.0001, max_lr=lr, step_size_up=10, mode="triangular2")

# BEGIN RECORDING THE TIME
start_time = time.time()

confusion_matrix, accuracy, recalls, precisions, fScores, grads, epoch_counts = train_congestion_avoider_10classes(cls_num, trainloader_full, trainloaders, device, model, optimizer, criterion, boolean_values, grads, epoch_counts)

CUDA device used...
Files already downloaded and verified
Files already downloaded and verified


In [ ]:
train_acc, train_P, train_R, train_F, test_acc, test_P, test_R, test_F, cong_events = get_cong_avoidance_results_10classes(epochs=100, min_cond=0, max_cond = 0, mult=0, lr=0.1, min_epochs = 5, num_class_avg=8, min_gradient=0)

CUDA device used...
Files already downloaded and verified
Files already downloaded and verified

********** EPOCH 1 **********
Learning rate:  0.0001


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:74: RuntimeWarning: invalid value encountered in double_scalars


No condition is met ..... 0.00%
time: 19.274 sec
Rows: Actual, Columns: Predicted
[[808. 131.  53.   7.   1.   0.   0.   0.   0.   0.]
 [374. 194.  26.   4.   1.   0.   0.   0.   0.   0.]
 [195.  98.  62.   4.   0.   0.   0.   0.   0.   0.]
 [112.  57.  43.   3.   0.   0.   0.   0.   0.   0.]
 [ 61.  25.  43.   0.   0.   0.   0.   0.   0.   0.]
 [ 50.  16.  10.   1.   0.   0.   0.   0.   0.   0.]
 [ 27.  11.   8.   0.   0.   0.   0.   0.   0.   0.]
 [ 14.  13.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.   5.   1.   0.   0.   0.   0.   0.   0.   0.]
 [  3.   7.   0.   0.   0.   0.   0.   0.   0.   0.]]
Class 0 A: : 43.059% (1067/2478)
Class 0 P: : 48.851% (808/1000)
Class 0 R: : 80.800% (808/1654)
Class 0 F: : 60.889%
********************
Class 1 A: : 43.059% (1067/2478)
Class 1 P: : 34.829% (194/599)
Class 1 R: : 32.387% (194/557)
Class 1 F: : 33.564%
********************
Class 2 A: : 43.059% (1067/2478)
Class 2 P: : 25.203% (62/359)
Class 2 R: : 17.270% (62/246)
Class 2 F: : 20.49

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:70: RuntimeWarning: invalid value encountered in double_scalars


Streaming output truncated to the last 5000 lines.
Learning rate:  0.020080000000000018
No condition is met ..... 0.00%
time: 363.871 sec
Rows: Actual, Columns: Predicted
[[946.  20.  16.   5.   8.   2.   1.   2.   0.   0.]
 [ 38. 549.   5.   4.   0.   0.   3.   0.   0.   0.]
 [ 53.   3. 244.  25.  15.  14.   5.   0.   0.   0.]
 [ 18.   5.  26. 133.  14.  14.   5.   0.   0.   0.]
 [ 16.   2.  25.  11.  70.   0.   5.   0.   0.   0.]
 [  7.   1.  12.  27.   5.  25.   0.   0.   0.   0.]
 [  1.   3.   8.   9.   3.   1.  21.   0.   0.   0.]
 [  2.   0.   3.   3.   4.   3.   0.  12.   0.   0.]
 [ 10.   2.   0.   0.   0.   0.   0.   0.   4.   0.]
 [  7.   3.   0.   0.   0.   0.   0.   0.   0.   0.]]
Class 0 A: : 80.872% (2004/2478)
Class 0 P: : 86.157% (946/1000)
Class 0 R: : 94.600% (946/1098)
Class 0 F: : 90.181%
********************
Class 1 A: : 80.872% (2004/2478)
Class 1 P: : 93.367% (549/599)
Class 1 R: : 91.653% (549/588)
Class 1 F: : 92.502%
********************
Class 2 A: : 80.872% (

In [ ]:
import pickle

with open('CIFAR10_LongTail.pickle', 'wb') as file:
    pickle.dump(train_acc, file)
    pickle.dump(train_P, file)
    pickle.dump(train_R, file)
    pickle.dump(train_F, file)
    pickle.dump(test_acc, file)
    pickle.dump(test_P, file)
    pickle.dump(test_R, file)
    pickle.dump(test_F, file)
    pickle.dump(cong_events, file)

In [63]:
train_acc, train_P, train_R, train_F, test_acc, test_P, test_R, test_F, cong_events = get_cong_avoidance_results_10classes(epochs=100, min_cond=0.5, max_cond = 0.5, mult=0.5, lr=0.1, min_epochs = 10, num_class_avg=8, min_gradient=0)

CUDA device used...
Files already downloaded and verified
Files already downloaded and verified

********** EPOCH 1 **********
Learning rate:  0.0001
Epoch counts:  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:72: RuntimeWarning: invalid value encountered in double_scalars


TOTAL GRAIDENTS:
{'layer1': {0: 1.1062144605675712, 1: 0.6434647483256413, 2: 1.8538399358512834, 3: 0.3495557830610778, 4: 1.3304171753989067, 5: 37.40489576291293, 6: 0.17000894966622582, 7: 0.5376712416909868, 8: 0.1349494505666371, 9: 0, 'total': 43.53101750804126}, 'layer2': {0: 2.2740909891435876, 1: 1.3131392000213964, 2: 3.145008298684843, 3: 0.674812832949101, 4: 2.299232038029004, 5: 62.304350580088794, 6: 0.314917760573735, 7: 0.9519184243254131, 8: 0.24534689226129558, 9: 0, 'total': 73.52281701607717}, 'layer3': {0: 4.999816300085513, 1: 2.8664908647479024, 2: 5.134019355929922, 3: 1.3568822735833237, 4: 3.4929530470981263, 5: 88.46015704516321, 6: 0.575955544009048, 7: 1.5571117947401945, 8: 0.4330414340874995, 9: 0, 'total': 108.87642765944474}, 'layer4': {0: 5.076100387959741, 1: 2.889049941644771, 2: 3.2361793322779704, 3: 1.264833228342468, 4: 2.0979046194115654, 5: 8.904718341422267, 6: 0.45512846528799855, 7: 1.0159724544209894, 8: 0.31798679077473935, 9: 0, 'total'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:68: RuntimeWarning: invalid value encountered in double_scalars


Streaming output truncated to the last 5000 lines.
Class 2 F: : 1.932%
********************
Class 3 A: : 42.938% (1064/2478)
Class 3 P: : 0.000% (0/215)
Class 3 R: : 0.000% (0/0)
Class 3 F: : 0.000%
********************
Class 4 A: : 42.938% (1064/2478)
Class 4 P: : 0.000% (0/129)
Class 4 R: : 0.000% (0/0)
Class 4 F: : 0.000%
********************
Class 5 A: : 42.938% (1064/2478)
Class 5 P: : 0.000% (0/77)
Class 5 R: : 0.000% (0/0)
Class 5 F: : 0.000%
********************
Class 6 A: : 42.938% (1064/2478)
Class 6 P: : 0.000% (0/46)
Class 6 R: : 0.000% (0/1)
Class 6 F: : 0.000%
********************
Class 7 A: : 42.938% (1064/2478)
Class 7 P: : 0.000% (0/27)
Class 7 R: : 0.000% (0/0)
Class 7 F: : 0.000%
********************
Class 8 A: : 42.938% (1064/2478)
Class 8 P: : 0.000% (0/16)
Class 8 R: : 0.000% (0/0)
Class 8 F: : 0.000%
********************

********** EPOCH 32 **********
Learning rate:  0.04505500000000002
Epoch counts:  [1, 0, 0, 11, 4, 6, 31, 31, 31, 31]
TOTAL GRAIDENTS:
{'layer1

In [64]:
import pickle

with open('cond500_mult050_min10epochs_avg8class_min0grad.pickle', 'wb') as file:
    pickle.dump(train_acc, file)
    pickle.dump(train_P, file)
    pickle.dump(train_R, file)
    pickle.dump(train_F, file)
    pickle.dump(test_acc, file)
    pickle.dump(test_P, file)
    pickle.dump(test_R, file)
    pickle.dump(test_F, file)
    pickle.dump(cong_events, file)

In [66]:
train_acc, train_P, train_R, train_F, test_acc, test_P, test_R, test_F, cong_events = get_cong_avoidance_results_10classes(epochs=100, min_cond=0.5, max_cond = 0.5, mult=0.5, lr=0.1, min_epochs = 10, num_class_avg=8, min_gradient=0)

CUDA device used...
Files already downloaded and verified
Files already downloaded and verified

********** EPOCH 1 **********
Learning rate:  0.0001
Epoch counts:  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
TOTAL GRAIDENTS:
{'layer1': {0: 0.9558136794366874, 1: 0.5854080164863262, 2: 1.6265593678690493, 3: 0.3708656680973945, 4: 1.2682312058168463, 5: 5.6658808989450336, 6: 0.1458163938987127, 7: 0.4057046357920626, 8: 0.14272453332523583, 9: 0, 'total': 11.167004399667348}, 'layer2': {0: 1.8528601747530047, 1: 1.1698102288501104, 2: 2.899559693702031, 3: 0.6957809316809289, 4: 2.119898961915169, 5: 9.810730158817023, 6: 0.2652888319098565, 7: 0.7198925832199166, 8: 0.2583617869531736, 9: 0, 'total': 19.792183351801214}, 'layer3': {0: 4.187630997708766, 1: 2.5842332849861123, 2: 4.6865147246280685, 3: 1.4106987690902315, 4: 3.457242959586438, 5: 14.667125647887588, 6: 0.4832104470769991, 7: 1.2526964525677613, 8: 0.45429335305743734, 9: 0, 'total': 33.1836466365894}, 'layer4': {0: 4.1493415791774

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:72: RuntimeWarning: invalid value encountered in double_scalars
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:68: RuntimeWarning: invalid value encountered in double_scalars


Streaming output truncated to the last 5000 lines.
Class 2 F: : 35.472%
********************
Class 3 A: : 49.596% (1229/2478)
Class 3 P: : 0.000% (0/215)
Class 3 R: : 0.000% (0/0)
Class 3 F: : 0.000%
********************
Class 4 A: : 49.596% (1229/2478)
Class 4 P: : 0.000% (0/129)
Class 4 R: : 0.000% (0/0)
Class 4 F: : 0.000%
********************
Class 5 A: : 49.596% (1229/2478)
Class 5 P: : 0.000% (0/77)
Class 5 R: : 0.000% (0/0)
Class 5 F: : 0.000%
********************
Class 6 A: : 49.596% (1229/2478)
Class 6 P: : 0.000% (0/46)
Class 6 R: : 0.000% (0/0)
Class 6 F: : 0.000%
********************
Class 7 A: : 49.596% (1229/2478)
Class 7 P: : 0.000% (0/27)
Class 7 R: : 0.000% (0/0)
Class 7 F: : 0.000%
********************
Class 8 A: : 49.596% (1229/2478)
Class 8 P: : 0.000% (0/16)
Class 8 R: : 0.000% (0/0)
Class 8 F: : 0.000%
********************

********** EPOCH 32 **********
Learning rate:  0.04505500000000002
Epoch counts:  [0, 0, 3, 6, 7, 21, 31, 31, 31, 31]
TOTAL GRAIDENTS:
{'layer

In [67]:
with open('cond500_mult050_min10epochs_avg8class_min0grad_layer3Onwards.pickle', 'wb') as file:
    pickle.dump(train_acc, file)
    pickle.dump(train_P, file)
    pickle.dump(train_R, file)
    pickle.dump(train_F, file)
    pickle.dump(test_acc, file)
    pickle.dump(test_P, file)
    pickle.dump(test_R, file)
    pickle.dump(test_F, file)
    pickle.dump(cong_events, file)

In [18]:
train_acc, train_P, train_R, train_F, test_acc, test_P, test_R, test_F, cong_events = get_cong_avoidance_results_10classes(epochs=100, min_cond=0.5, max_cond = 0.5, mult=0.5, lr=0.1, min_epochs = 10, num_class_avg=8, min_gradient=0)

CUDA device used...
Files already downloaded and verified
Files already downloaded and verified

********** EPOCH 1 **********
Learning rate:  0.0001
Epoch counts:  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:72: RuntimeWarning: invalid value encountered in double_scalars


TOTAL GRAIDENTS:
{'layer1': {0: 1.0150998122117016, 1: 0.634218737934134, 2: 1.9516481444006786, 3: 0.35427543745026924, 4: 1.0204990819911472, 5: 18.4010043409653, 6: 0.15714644673425937, 7: 0.4984197930752998, 8: 0.12510915911116172, 9: 0, 'total': 24.157420953873952}, 'layer2': {0: 2.0419175575952977, 1: 1.2501579466916155, 2: 3.5684910200652666, 3: 0.67909643240273, 4: 1.897041197429644, 5: 32.139676534570754, 6: 0.29452401725939126, 7: 0.9032432519597933, 8: 0.22499679845714127, 9: 0, 'total': 42.99914475643163}, 'layer3': {0: 4.689830229734071, 1: 2.73161944388994, 2: 5.857104432478081, 3: 1.3702623470308026, 4: 3.0488635246874765, 5: 47.541230344213545, 6: 0.5435512310650665, 7: 1.5189748272387078, 8: 0.40353098142441013, 9: 0, 'total': 67.7049673617621}, 'layer4': {0: 4.682987783220597, 1: 2.6614806316501927, 2: 3.0125896889949217, 3: 1.2078009673277847, 4: 1.82781339486246, 5: 6.679582601092989, 6: 0.41639331602709717, 7: 1.0162062646631966, 8: 0.2975394172099186, 9: 0, 'total

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:68: RuntimeWarning: invalid value encountered in double_scalars


Streaming output truncated to the last 5000 lines.
Class 2 F: : 0.000%
********************
Class 3 A: : 40.355% (1000/2478)
Class 3 P: : 0.000% (0/215)
Class 3 R: : 0.000% (0/0)
Class 3 F: : 0.000%
********************
Class 4 A: : 40.355% (1000/2478)
Class 4 P: : 0.000% (0/129)
Class 4 R: : 0.000% (0/0)
Class 4 F: : 0.000%
********************
Class 5 A: : 40.355% (1000/2478)
Class 5 P: : 0.000% (0/77)
Class 5 R: : 0.000% (0/0)
Class 5 F: : 0.000%
********************
Class 6 A: : 40.355% (1000/2478)
Class 6 P: : 0.000% (0/46)
Class 6 R: : 0.000% (0/0)
Class 6 F: : 0.000%
********************
Class 7 A: : 40.355% (1000/2478)
Class 7 P: : 0.000% (0/27)
Class 7 R: : 0.000% (0/0)
Class 7 F: : 0.000%
********************
Class 8 A: : 40.355% (1000/2478)
Class 8 P: : 0.000% (0/16)
Class 8 R: : 0.000% (0/0)
Class 8 F: : 0.000%
********************

********** EPOCH 32 **********
Learning rate:  0.04505500000000002
Epoch counts:  [1, 1, 4, 9, 31, 31, 31, 21, 31, 31]
TOTAL GRAIDENTS:
{'layer

In [20]:
import pickle
with open('cond500_mult050_min10epochs_avg8class_min0grad_layer4onwards.pickle', 'wb') as file:
    pickle.dump(train_acc, file)
    pickle.dump(train_P, file)
    pickle.dump(train_R, file)
    pickle.dump(train_F, file)
    pickle.dump(test_acc, file)
    pickle.dump(test_P, file)
    pickle.dump(test_R, file)
    pickle.dump(test_F, file)
    pickle.dump(cong_events, file)

In [21]:
train_acc, train_P, train_R, train_F, test_acc, test_P, test_R, test_F, cong_events = get_cong_avoidance_results_10classes(epochs=100, min_cond=0.5, max_cond = 0.5, mult=0.1, lr=0.1, min_epochs = 10, num_class_avg=8, min_gradient=0)

CUDA device used...
Files already downloaded and verified
Files already downloaded and verified

********** EPOCH 1 **********
Learning rate:  0.0001
Epoch counts:  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
TOTAL GRAIDENTS:
{'layer1': {0: 0.977775536943227, 1: 0.6382395703258226, 2: 2.0189549817005172, 3: 0.36266654011706123, 4: 1.0699882612389047, 5: 4.455257520603482, 6: 0.16251045904209604, 7: 0.4315503182442626, 8: 0.13405924920152756, 9: 0, 'total': 10.2510024374169}, 'layer2': {0: 1.9778471926110797, 1: 1.2711445956229, 2: 3.432285559887532, 3: 0.6912403204623843, 4: 1.9935076395631768, 5: 7.551656645606272, 6: 0.30178720136973425, 7: 0.7903595410462003, 8: 0.2398140971963585, 9: 0, 'total': 18.249642793365638}, 'layer3': {0: 4.294241405790672, 1: 2.7859083946677856, 2: 5.461809592670761, 3: 1.3835392655892065, 4: 3.197008657036349, 5: 10.861448486451991, 6: 0.5545593108945468, 7: 1.3281254076573532, 8: 0.41523130428322474, 9: 0, 'total': 30.28187182504189}, 'layer4': {0: 4.452863956685178,

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:68: RuntimeWarning: invalid value encountered in double_scalars


TOTAL GRAIDENTS:
{'layer1': {0: 107.44529341161251, 1: 66.60646995622665, 2: 240.9136482104659, 3: 44.70336144324392, 4: 131.15206389129162, 5: 639.7366962581873, 6: 20.301304657943547, 7: 57.276686212047935, 8: 17.409491882659495, 9: 0, 'total': 1325.5450159236789}, 'layer2': {0: 207.61393935978413, 1: 135.68639891594648, 2: 413.6207496598363, 3: 82.75707793980837, 4: 234.82542767375708, 5: 1050.8338015824556, 6: 38.10469733271748, 7: 104.80202481895685, 8: 30.807156501337886, 9: 0, 'total': 2299.0512737846}, 'layer3': {0: 460.479505173862, 1: 306.10914942249656, 2: 677.5157965421677, 3: 169.24905317183584, 4: 378.9643886163831, 5: 1432.0467263907194, 6: 69.64787609968334, 7: 174.35009752959013, 8: 52.94481144146994, 9: 0, 'total': 3721.307404388208}, 'layer4': {0: 521.7964143753052, 1: 338.589476455003, 2: 395.09786089509726, 3: 169.66246386803687, 4: 224.3890480864793, 5: 499.29879409074783, 6: 59.061789555475116, 7: 115.91332918219268, 8: 40.03800608916208, 9: 0, 'total': 2363.8471

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:72: RuntimeWarning: invalid value encountered in double_scalars


Streaming output truncated to the last 5000 lines.
Class 2 F: : 0.000%
********************
Class 3 A: : 49.556% (1228/2478)
Class 3 P: : 0.000% (0/215)
Class 3 R: : 0.000% (0/0)
Class 3 F: : 0.000%
********************
Class 4 A: : 49.556% (1228/2478)
Class 4 P: : 0.000% (0/129)
Class 4 R: : 0.000% (0/0)
Class 4 F: : 0.000%
********************
Class 5 A: : 49.556% (1228/2478)
Class 5 P: : 0.000% (0/77)
Class 5 R: : 0.000% (0/0)
Class 5 F: : 0.000%
********************
Class 6 A: : 49.556% (1228/2478)
Class 6 P: : 0.000% (0/46)
Class 6 R: : 0.000% (0/0)
Class 6 F: : 0.000%
********************
Class 7 A: : 49.556% (1228/2478)
Class 7 P: : 0.000% (0/27)
Class 7 R: : 0.000% (0/0)
Class 7 F: : 0.000%
********************
Class 8 A: : 49.556% (1228/2478)
Class 8 P: : 0.000% (0/16)
Class 8 R: : 0.000% (0/0)
Class 8 F: : 0.000%
********************

********** EPOCH 32 **********
Learning rate:  0.04505500000000002
Epoch counts:  [1, 1, 10, 9, 31, 1, 31, 21, 31, 31]
TOTAL GRAIDENTS:
{'layer

In [22]:
with open('cond500_mult010_min10epochs_avg8class_min0grad_layer4onwards.pickle', 'wb') as file:
    pickle.dump(train_acc, file)
    pickle.dump(train_P, file)
    pickle.dump(train_R, file)
    pickle.dump(train_F, file)
    pickle.dump(test_acc, file)
    pickle.dump(test_P, file)
    pickle.dump(test_R, file)
    pickle.dump(test_F, file)
    pickle.dump(cong_events, file)